-- MySQL Script generated by MySQL Workbench
-- Wed Apr 18 00:56:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd` ;

-- -----------------------------------------------------
-- Schema bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd` DEFAULT CHARACTER SET latin1 ;
USE `bd` ;

-- -----------------------------------------------------
-- Table `bd`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`cargo` ;

CREATE TABLE IF NOT EXISTS `bd`.`cargo` (
  `idCargos` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`idCargos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd`.`seccional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`seccional` ;

CREATE TABLE IF NOT EXISTS `bd`.`seccional` (
  `idSeccional` INT(11) NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `liderProceso` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSeccional`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`empleado` ;

CREATE TABLE IF NOT EXISTS `bd`.`empleado` (
  `cedula` BIGINT(50) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(3) NOT NULL,
  `idSeccional` INT(11) NOT NULL,
  `idCargos` INT(11) NOT NULL,
  PRIMARY KEY (`cedula`, `idSeccional`, `idCargos`),
  INDEX `fk_empleado_seccional_idx` (`idSeccional` ASC),
  INDEX `fk_empleado_cargo1_idx` (`idCargos` ASC),
  CONSTRAINT `fk_empleado_seccional`
    FOREIGN KEY (`idSeccional`)
    REFERENCES `bd`.`seccional` (`idSeccional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_cargo1`
    FOREIGN KEY (`idCargos`)
    REFERENCES `bd`.`cargo` (`idCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`cuenta` ;

CREATE TABLE IF NOT EXISTS `bd`.`cuenta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(45) NOT NULL,
  `empleado_cedula` BIGINT(50) NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`,`empleado_cedula`),
  INDEX `fk_cuenta_empleado_idx` (`empleado_cedula` ASC),
  CONSTRAINT `fk_cuenta_empleado`
    FOREIGN KEY (`empleado_cedula`)
    REFERENCES `bd`.`empleado` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`registro` ;

CREATE TABLE IF NOT EXISTS `bd`.`registro` (
  `idRegistro` INT(11) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idRegistro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`cuenta_has_registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`cuenta_has_registro` ;

CREATE TABLE IF NOT EXISTS `bd`.`cuenta_has_registro` (
  `cuenta_id` INT NOT NULL,
  `cuenta_cedula` BIGINT(50) NOT NULL,
  `cuenta_idSeccional` INT(11) NOT NULL,
  `cuenta_idCargos` INT(11) NOT NULL,
  `registro_idRegistro` INT(11) NOT NULL,
  PRIMARY KEY (`cuenta_id`, `cuenta_cedula`, `cuenta_idSeccional`, `cuenta_idCargos`, `registro_idRegistro`),
  INDEX `fk_cuenta_has_registro_registro1_idx` (`registro_idRegistro` ASC),
  INDEX `fk_cuenta_has_registro_cuenta1_idx` (`cuenta_id` ASC, `cuenta_cedula` ASC, `cuenta_idSeccional` ASC, `cuenta_idCargos` ASC),
  CONSTRAINT `fk_cuenta_has_registro_cuenta1`
    FOREIGN KEY (`cuenta_id`)
    REFERENCES `bd`.`cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_has_registro_registro1`
    FOREIGN KEY (`registro_idRegistro`)
    REFERENCES `bd`.`registro` (`idRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd`.`registro_has_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd`.`registro_has_cuenta` ;

CREATE TABLE IF NOT EXISTS `bd`.`registro_has_cuenta` (
  `registro_idRegistro` INT(11) NOT NULL,
  `cuenta_id` INT NOT NULL,
  `cuenta_empleado_cedula` BIGINT(50) NOT NULL,
  PRIMARY KEY (`registro_idRegistro`, `cuenta_id`, `cuenta_empleado_cedula`),
  INDEX `fk_registro_has_cuenta_cuenta1_idx` (`cuenta_id` ASC, `cuenta_empleado_cedula` ASC),
  INDEX `fk_registro_has_cuenta_registro1_idx` (`registro_idRegistro` ASC),
  CONSTRAINT `fk_registro_has_cuenta_registro1`
    FOREIGN KEY (`registro_idRegistro`)
    REFERENCES `bd`.`registro` (`idRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_has_cuenta_cuenta1`
    FOREIGN KEY (`cuenta_id` , `cuenta_empleado_cedula`)
    REFERENCES `bd`.`cuenta` (`id` , `empleado_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `cuenta` ( `contrasena`, `empleado_cedula`) VALUES
('UbcFeuR35Wcuy+vusRINTg==', 123456 ),
( 'UbcFeuR35Wcuy+vusRINTg==', 456789),
( 'UbcFeuR35Wcuy+vusRINTg==', 251721 ),
( 'UbcFeuR35Wcuy+vusRINTg==', 789123 ),
( 'UbcFeuR35Wcuy+vusRINTg==', 1012456674 ),
( 'UbcFeuR35Wcuy+vusRINTg==', 98092420329 );

--
-- Volcado de datos para la tabla `empleado`
--

INSERT INTO `empleado` (`cedula`, `nombre`, `apellido`, `email`, `telefono`, `direccion`, `numero`, `sexo`, `idSeccional`, `idCargos`) VALUES
(123456, 'Alfredo', 'Rodríguez', 'alfredo@andreslargo.com', '31234', 'Cll 21 ', '346123', 'm', 1,0),
(456789, 'Emilio', 'Rodríguez', 'emilio@andreslargo.com', '1234', 'Cll 211 ', '343', 'm', 1,1),
(789123, 'Wanda', 'Velasquez', 'wanda@andreslargo.com', '334', 'Cll 21 ', '343', 'f', 1,2),
(1012456674, 'José', 'Rodríguez', 'asd@andreslargo.com', '3456', 'Cll 18 X', '346', 'm', 1,3),
(98092420329, 'Andres é', 'Cuenca Pérez', 'cohchino@andreslargo.com', '3228456', 'Cll 18 B', '3646', 'm', 1,4);